/* ============================================================
   Datei:   js/spickzettel.js
   Zweck:   Inhalte für die rechte Spalte: die Reihenfolge einer
            Abfrage, alle Begriffe (kurz = Zeile im zugeklappten
            Zustand, wann/syntax/beispiel = aufgeklappt) und die
            fertigen Beispiele.
   ============================================================ */

window.Spielplatz = window.Spielplatz || {};

/* --- 1. Reihenfolge der Teile einer Abfrage (ziel = id eines Begriffs) --- */
Spielplatz.REIHENFOLGE = [
  { teil: 'SELECT', ziel: 'select', pflicht: true },
  { teil: 'FROM', ziel: 'select', pflicht: true },
  { teil: 'JOIN', ziel: 'join' },
  { teil: 'WHERE', ziel: 'where' },
  { teil: 'GROUP BY', ziel: 'group-by' },
  { teil: 'HAVING', ziel: 'having' },
  { teil: 'ORDER BY', ziel: 'order-by' },
  { teil: 'LIMIT', ziel: 'limit' },
];

/* --- 2. Begriffe, nach Themen gruppiert --- */
Spielplatz.BEGRIFFE = [
  {
    titel: 'Grundlagen',
    begriffe: [
      {
        id: 'select',
        begriff: 'SELECT … FROM',
        kurz: 'Spalten aus einer Tabelle holen',
        wann: 'Immer, wenn du Daten sehen willst. Damit beginnt fast jede Abfrage: SELECT nennt die Spalten, FROM die Tabelle.',
        syntax: 'SELECT spalte1, spalte2\nFROM tabelle;',
        beispiel: 'SELECT bezeichnung, preis\nFROM artikel;',
      },
      {
        id: 'stern',
        begriff: '*',
        kurz: 'Alle Spalten auf einmal',
        wann: 'Wenn du alle Spalten sehen willst, ohne sie einzeln aufzuzählen.',
        syntax: 'SELECT * FROM tabelle;',
        beispiel: 'SELECT * FROM mitarbeiter;',
        hinweis: 'Praktisch zum Erkunden. In echten Programmen nennt man die Spalten besser einzeln.',
      },
      {
        id: 'as',
        begriff: 'AS',
        kurz: 'Spalte oder Tabelle umbenennen',
        wann: 'Wenn eine Spalte im Ergebnis einen verständlichen Namen bekommen soll. Auch Tabellen kannst du so abkürzen.',
        syntax: 'SELECT spalte AS neuer_name\nFROM tabelle t;',
        beispiel: 'SELECT bezeichnung AS artikel,\n       preis * bestand AS lagerwert\nFROM artikel;',
      },
      {
        id: 'distinct',
        begriff: 'DISTINCT',
        kurz: 'Doppelte Werte entfernen',
        wann: 'Wenn doppelte Werte im Ergebnis nur einmal erscheinen sollen.',
        syntax: 'SELECT DISTINCT spalte FROM tabelle;',
        beispiel: 'SELECT DISTINCT stadt FROM kunden;',
      },
      {
        id: 'kommentar',
        begriff: '-- Kommentar',
        kurz: 'Notiz, die ignoriert wird',
        wann: 'Für Notizen im Code. Alles hinter -- bis zum Zeilenende wird ignoriert.',
        syntax: '-- Das hier liest die Datenbank nicht',
        beispiel: "-- Alle Kunden aus Berlin\nSELECT * FROM kunden\nWHERE stadt = 'Berlin';",
      },
    ],
  },
  {
    titel: 'Eigene Tabellen anlegen',
    begriffe: [
      {
        id: 'create',
        begriff: 'CREATE TABLE',
        kurz: 'Neue Tabelle anlegen',
        wann: 'Um eine neue Tabelle anzulegen. Du legst den Bauplan fest: welche Spalten es gibt und welchen Datentyp jede hat.',
        syntax: 'CREATE TABLE name (\n  id INTEGER PRIMARY KEY,\n  spalte TEXT NOT NULL,\n  zahl REAL\n);',
        beispiel: "DROP TABLE IF EXISTS fahrzeuge; -- falls es sie schon gibt\nCREATE TABLE fahrzeuge (\n  id INTEGER PRIMARY KEY,\n  bezeichnung TEXT NOT NULL,\n  baujahr INTEGER\n);\n\nINSERT INTO fahrzeuge (bezeichnung, baujahr)\nVALUES ('Stapler 1', 2019), ('Ameise 3', 2022);\n\nSELECT * FROM fahrzeuge;",
        hinweis: 'Die neue Tabelle erscheint sofort links unter „Deine Tabellen“. Schritt für Schritt erklärt im Reiter „Eigene Tabelle“ in der Mitte.',
      },
      {
        id: 'datentypen',
        begriff: 'INTEGER · REAL · TEXT',
        kurz: 'Datentypen: welche Art von Wert',
        wann: 'Beim Anlegen bekommt jede Spalte einen Typ: INTEGER für ganze Zahlen, REAL für Kommazahlen, TEXT für Text. Kommazahlen schreibst du mit Punkt: 19.99.',
        syntax: 'alter INTEGER,\npreis REAL,\nname TEXT',
        beispiel: "SELECT typeof(42) AS ganze_zahl,\n       typeof(19.99) AS kommazahl,\n       typeof('Hamburg') AS text,\n       typeof(NULL) AS leer;",
      },
      {
        id: 'regeln',
        begriff: 'PRIMARY KEY · NOT NULL',
        kurz: 'Regeln für Spalten',
        wann: 'PRIMARY KEY macht eine Spalte zur eindeutigen Nummer jeder Zeile. NOT NULL macht sie zum Pflichtfeld. REFERENCES sagt, auf welche Tabelle eine Spalte verweist.',
        syntax: 'id INTEGER PRIMARY KEY,\nname TEXT NOT NULL,\nkunde_id INTEGER REFERENCES kunden(id)',
        beispiel: "CREATE TABLE IF NOT EXISTS lagerorte (\n  id INTEGER PRIMARY KEY,\n  regal TEXT NOT NULL,\n  artikel_id INTEGER REFERENCES artikel(id)\n);\n\nINSERT INTO lagerorte (regal, artikel_id)\nVALUES ('A-01', 4);\n\nSELECT * FROM lagerorte;",
        hinweis: 'Die id musst du beim Einfügen nicht angeben – PRIMARY KEY vergibt sie automatisch.',
      },
      {
        id: 'insert',
        begriff: 'INSERT INTO',
        kurz: 'Zeilen hinzufügen',
        wann: 'Um neue Zeilen anzulegen – eine oder mehrere auf einmal, getrennt durch Kommas.',
        syntax: 'INSERT INTO tabelle (spalte1, spalte2)\nVALUES (wert1, wert2),\n       (wert3, wert4);',
        beispiel: "INSERT INTO kunden (name, stadt) VALUES\n  ('Spedition Krause', 'Bremen'),\n  ('Hafenlogistik Ost', 'Rostock');\n\nSELECT * FROM kunden;",
        hinweis: 'Lässt du die id weg, vergibt SQLite sie selbst.',
      },
      {
        id: 'alter',
        begriff: 'ALTER TABLE',
        kurz: 'Spalte nachträglich hinzufügen',
        wann: 'Wenn eine vorhandene Tabelle eine weitere Spalte bekommen soll. Bestehende Zeilen haben dort erst einmal NULL.',
        syntax: 'ALTER TABLE tabelle\nADD COLUMN spalte TYP;',
        beispiel: "ALTER TABLE kunden ADD COLUMN telefon TEXT;\n\nUPDATE kunden SET telefon = '040 123456'\nWHERE id = 1;\n\nSELECT * FROM kunden;",
      },
      {
        id: 'drop',
        begriff: 'DROP TABLE',
        kurz: 'Tabelle löschen',
        wann: 'Um eine Tabelle samt Inhalt komplett zu entfernen. IF EXISTS verhindert einen Fehler, wenn es sie gar nicht gibt.',
        syntax: 'DROP TABLE IF EXISTS tabelle;',
        beispiel: '-- Erst eine Übungstabelle anlegen …\nCREATE TABLE papierkorb (id INTEGER);\n\n-- … und gleich wieder löschen\nDROP TABLE papierkorb;',
        hinweis: 'Gelöscht ist gelöscht – wenn du es selbst ausführst. Hast du dich vertan, holt „Zurücksetzen“ oben rechts alles zurück.',
      },
    ],
  },
  {
    titel: 'Filtern',
    begriffe: [
      {
        id: 'where',
        begriff: 'WHERE',
        kurz: 'Nur bestimmte Zeilen behalten',
        wann: 'Wenn nur bestimmte Zeilen ins Ergebnis sollen. Steht direkt nach FROM (und nach einem JOIN).',
        syntax: 'SELECT * FROM tabelle\nWHERE bedingung;',
        beispiel: "SELECT * FROM artikel\nWHERE kategorie = 'Technik';",
        hinweis: "Text steht in einfachen Anführungszeichen 'so', Zahlen ohne.",
      },
      {
        id: 'vergleich',
        begriff: '=  <>  <  >  <=  >=',
        kurz: 'Werte vergleichen',
        wann: 'Zum Vergleichen von Zahlen, Texten und Datumswerten. <> bedeutet „ungleich“.',
        syntax: 'WHERE spalte >= wert',
        beispiel: 'SELECT vorname, nachname, gehalt\nFROM mitarbeiter\nWHERE gehalt >= 4000;',
      },
      {
        id: 'and-or',
        begriff: 'AND · OR · NOT',
        kurz: 'Bedingungen verknüpfen',
        wann: 'Wenn mehrere Bedingungen gleichzeitig gelten sollen (AND), eine von mehreren reicht (OR) oder etwas nicht zutreffen darf (NOT).',
        syntax: 'WHERE a AND (b OR c)',
        beispiel: "SELECT * FROM artikel\nWHERE kategorie = 'Schutz'\n  AND preis < 20;",
        hinweis: 'Mischst du AND und OR, setze Klammern. Sonst gilt AND zuerst.',
      },
      {
        id: 'between',
        begriff: 'BETWEEN',
        kurz: 'Bereich von … bis',
        wann: 'Für einen Bereich von … bis. Beide Grenzen gehören dazu.',
        syntax: 'WHERE spalte BETWEEN von AND bis',
        beispiel: "SELECT * FROM bestellungen\nWHERE datum BETWEEN '2026-02-01' AND '2026-03-31';",
      },
      {
        id: 'in',
        begriff: 'IN',
        kurz: 'Wert aus einer Liste',
        wann: 'Wenn ein Wert in einer Liste vorkommen soll. Kürzer als viele OR hintereinander.',
        syntax: "WHERE spalte IN ('a', 'b', 'c')",
        beispiel: "SELECT * FROM kunden\nWHERE stadt IN ('Berlin', 'Hamburg');",
      },
      {
        id: 'like',
        begriff: 'LIKE',
        kurz: 'Textsuche mit Platzhaltern',
        wann: 'Für die Suche in Texten. % steht für beliebig viele Zeichen, _ für genau ein Zeichen.',
        syntax: "WHERE spalte LIKE '%teil%'",
        beispiel: "SELECT * FROM artikel\nWHERE bezeichnung LIKE '%schuh%';",
        hinweis: 'In SQLite ist LIKE bei a–z egal, ob groß oder klein geschrieben.',
      },
      {
        id: 'is-null',
        begriff: 'IS NULL',
        kurz: 'Leere Felder finden',
        wann: 'Um leere Felder zu finden. NULL heißt „kein Wert“ – mit = NULL klappt das nicht.',
        syntax: 'WHERE spalte IS NULL\nWHERE spalte IS NOT NULL',
        beispiel: '-- Wer hat keinen Chef?\nSELECT vorname, nachname, position\nFROM mitarbeiter\nWHERE vorgesetzter_id IS NULL;',
      },
    ],
  },
  {
    titel: 'Sortieren und Begrenzen',
    begriffe: [
      {
        id: 'order-by',
        begriff: 'ORDER BY',
        kurz: 'Sortieren (ASC / DESC)',
        wann: 'Wenn das Ergebnis sortiert sein soll. ASC heißt aufsteigend (Standard), DESC absteigend.',
        syntax: 'ORDER BY spalte DESC, spalte2 ASC',
        beispiel: 'SELECT bezeichnung, preis\nFROM artikel\nORDER BY preis DESC;',
      },
      {
        id: 'limit',
        begriff: 'LIMIT · OFFSET',
        kurz: 'Nur die ersten Zeilen',
        wann: 'Wenn du nur die ersten Zeilen brauchst, zum Beispiel eine Top 3. OFFSET überspringt vorher Zeilen.',
        syntax: 'LIMIT anzahl OFFSET überspringen',
        beispiel: 'SELECT bezeichnung, preis\nFROM artikel\nORDER BY preis DESC\nLIMIT 3;',
      },
    ],
  },
  {
    titel: 'Rechnen und Zusammenfassen',
    begriffe: [
      {
        id: 'count',
        begriff: 'COUNT',
        kurz: 'Zeilen zählen',
        wann: 'Zählt Zeilen. COUNT(*) zählt alle, COUNT(spalte) nur die, in denen ein Wert steht.',
        syntax: 'SELECT COUNT(*) FROM tabelle;',
        beispiel: 'SELECT COUNT(*) AS anzahl\nFROM bestellungen;',
      },
      {
        id: 'sum-avg',
        begriff: 'SUM · AVG',
        kurz: 'Summe und Durchschnitt',
        wann: 'Summe und Durchschnitt einer Zahlenspalte.',
        syntax: 'SELECT SUM(spalte), AVG(spalte)\nFROM tabelle;',
        beispiel: 'SELECT SUM(gehalt) AS lohnkosten,\n       ROUND(AVG(gehalt), 2) AS durchschnitt\nFROM mitarbeiter;',
      },
      {
        id: 'min-max',
        begriff: 'MIN · MAX',
        kurz: 'Kleinster und größter Wert',
        wann: 'Der kleinste und der größte Wert einer Spalte.',
        syntax: 'SELECT MIN(spalte), MAX(spalte)\nFROM tabelle;',
        beispiel: 'SELECT MIN(preis) AS billigster,\n       MAX(preis) AS teuerster\nFROM artikel;',
      },
      {
        id: 'rechnen',
        begriff: '+ - * / · ROUND',
        kurz: 'Rechnen und runden',
        wann: 'Mit den Rechenzeichen rechnest du direkt in der Abfrage. ROUND(wert, 2) rundet auf zwei Nachkommastellen.',
        syntax: 'SELECT ROUND(spalte * 1.19, 2)\nFROM tabelle;',
        beispiel: 'SELECT bezeichnung,\n       preis AS netto,\n       ROUND(preis * 1.19, 2) AS brutto\nFROM artikel;',
      },
      {
        id: 'case',
        begriff: 'CASE WHEN',
        kurz: 'Wenn – dann – sonst',
        wann: 'Das „Wenn – dann – sonst“ von SQL. Zeigt je nach Bedingung einen anderen Wert an.',
        syntax: "CASE\n  WHEN bedingung THEN 'a'\n  ELSE 'b'\nEND",
        beispiel: "SELECT bezeichnung, bestand,\n  CASE\n    WHEN bestand = 0 THEN 'ausverkauft'\n    WHEN bestand < 20 THEN 'knapp'\n    ELSE 'ok'\n  END AS ampel\nFROM artikel;",
      },
    ],
  },
  {
    titel: 'Gruppieren',
    begriffe: [
      {
        id: 'group-by',
        begriff: 'GROUP BY',
        kurz: 'Je Gruppe rechnen',
        wann: 'Wenn du je Gruppe rechnen willst, zum Beispiel die Anzahl je Kategorie.',
        syntax: 'SELECT gruppe, COUNT(*)\nFROM tabelle\nGROUP BY gruppe;',
        beispiel: 'SELECT kategorie, COUNT(*) AS anzahl\nFROM artikel\nGROUP BY kategorie;',
        hinweis: 'Jede Spalte im SELECT muss entweder in GROUP BY stehen oder in einer Funktion wie COUNT oder SUM.',
      },
      {
        id: 'having',
        begriff: 'HAVING',
        kurz: 'Gruppen filtern',
        wann: 'Filtert Gruppen nach dem Gruppieren. WHERE filtert einzelne Zeilen davor.',
        syntax: 'GROUP BY gruppe\nHAVING SUM(spalte) > wert',
        beispiel: 'SELECT kategorie, SUM(bestand) AS stueck\nFROM artikel\nGROUP BY kategorie\nHAVING SUM(bestand) > 100;',
      },
    ],
  },
  {
    titel: 'Tabellen verbinden',
    begriffe: [
      {
        id: 'join',
        begriff: 'JOIN … ON',
        kurz: 'Zwei Tabellen verbinden',
        wann: 'Wenn Daten aus mehreren Tabellen zusammengehören. ON sagt, über welche Spalten sie verbunden sind.',
        syntax: 'FROM tabelle_a a\nJOIN tabelle_b b ON b.a_id = a.id',
        beispiel: 'SELECT m.vorname, m.nachname, a.name AS abteilung\nFROM mitarbeiter m\nJOIN abteilungen a ON a.id = m.abteilung_id;',
        hinweis: 'JOIN zeigt nur Zeilen, die in beiden Tabellen einen Partner haben.',
      },
      {
        id: 'left-join',
        begriff: 'LEFT JOIN',
        kurz: 'Verbinden, auch ohne Partner',
        wann: 'Wenn alle Zeilen der linken Tabelle bleiben sollen, auch ohne Partner. Was fehlt, wird NULL.',
        syntax: 'FROM a\nLEFT JOIN b ON b.a_id = a.id',
        beispiel: 'SELECT k.name, COUNT(b.id) AS bestellungen\nFROM kunden k\nLEFT JOIN bestellungen b ON b.kunde_id = k.id\nGROUP BY k.id;',
      },
      {
        id: 'mehrere-joins',
        begriff: 'Mehrere JOINs',
        kurz: 'Über mehrere Tabellen hinweg',
        wann: 'Für Wege über mehrere Tabellen, zum Beispiel Kunde → Bestellung → Position → Artikel.',
        syntax: 'FROM a\nJOIN b ON …\nJOIN c ON …',
        beispiel: 'SELECT k.name, a.bezeichnung, p.menge\nFROM positionen p\nJOIN bestellungen b ON b.id = p.bestellung_id\nJOIN kunden k ON k.id = b.kunde_id\nJOIN artikel a ON a.id = p.artikel_id;',
      },
      {
        id: 'self-join',
        begriff: 'Self-JOIN',
        kurz: 'Tabelle mit sich selbst verbinden',
        wann: 'Wenn eine Tabelle auf sich selbst verweist, zum Beispiel Mitarbeiter auf ihren Chef. Die Tabelle bekommt dafür zwei Abkürzungen.',
        syntax: 'FROM tabelle a\nJOIN tabelle b ON b.id = a.verweis_id',
        beispiel: "SELECT m.vorname || ' ' || m.nachname AS mitarbeiter,\n       c.vorname || ' ' || c.nachname AS chef\nFROM mitarbeiter m\nLEFT JOIN mitarbeiter c ON c.id = m.vorgesetzter_id;",
      },
      {
        id: 'unterabfrage',
        begriff: 'Unterabfrage',
        kurz: 'Abfrage in der Abfrage',
        wann: 'Wenn du das Ergebnis einer Abfrage in einer anderen brauchst. Sie steht in Klammern.',
        syntax: 'WHERE spalte > (SELECT …)',
        beispiel: '-- Wer verdient mehr als der Durchschnitt?\nSELECT vorname, nachname, gehalt\nFROM mitarbeiter\nWHERE gehalt > (SELECT AVG(gehalt) FROM mitarbeiter);',
      },
    ],
  },
  {
    titel: 'Daten ändern und löschen',
    begriffe: [
      {
        id: 'update',
        begriff: 'UPDATE … SET',
        kurz: 'Vorhandene Werte ändern',
        wann: 'Um vorhandene Werte zu ändern.',
        syntax: 'UPDATE tabelle\nSET spalte = wert\nWHERE bedingung;',
        beispiel: '-- Gehaltserhöhung für das Lager\nUPDATE mitarbeiter\nSET gehalt = gehalt * 1.05\nWHERE abteilung_id = 1;\n\nSELECT vorname, gehalt FROM mitarbeiter\nWHERE abteilung_id = 1;',
        hinweis: 'Ohne WHERE änderst du alle Zeilen! Das Beispiel hier ist nur eine Vorschau, die Übungsdaten bleiben unverändert.',
      },
      {
        id: 'delete',
        begriff: 'DELETE FROM',
        kurz: 'Zeilen löschen',
        wann: 'Um einzelne Zeilen zu löschen. Die Tabelle selbst bleibt bestehen.',
        syntax: 'DELETE FROM tabelle\nWHERE bedingung;',
        beispiel: "DELETE FROM bestellungen\nWHERE status = 'storniert';\n\nSELECT * FROM bestellungen;",
        hinweis: 'Ohne WHERE ist alles weg! Das Beispiel hier ist nur eine Vorschau, die Übungsdaten bleiben unverändert.',
      },
    ],
  },
  {
    titel: 'Text und Datum',
    begriffe: [
      {
        id: 'verketten',
        begriff: '||',
        kurz: 'Texte aneinanderhängen',
        wann: 'Um Texte aneinanderzuhängen.',
        syntax: "spalte1 || ' ' || spalte2",
        beispiel: "SELECT vorname || ' ' || nachname AS name,\n       position\nFROM mitarbeiter;",
      },
      {
        id: 'text-funktionen',
        begriff: 'UPPER · LOWER · LENGTH',
        kurz: 'Groß, klein, Länge',
        wann: 'Text in Groß- oder Kleinbuchstaben umwandeln oder die Zeichen zählen.',
        syntax: 'UPPER(spalte), LENGTH(spalte)',
        beispiel: 'SELECT UPPER(bezeichnung) AS gross,\n       LENGTH(bezeichnung) AS zeichen\nFROM artikel;',
      },
      {
        id: 'strftime',
        begriff: 'strftime',
        kurz: 'Teile aus einem Datum holen',
        wann: 'Um Teile aus einem Datum zu holen, zum Beispiel Monat (%m) oder Jahr (%Y). Das Datum steht hier als Text im Format JJJJ-MM-TT.',
        syntax: "strftime('%Y', datum)",
        beispiel: "SELECT strftime('%m', datum) AS monat,\n       COUNT(*) AS bestellungen\nFROM bestellungen\nGROUP BY monat;",
      },
    ],
  },
];

/* --- 3. Fertige Beispiele: echte Fragen an die Lager GmbH --- */
Spielplatz.BEISPIELE = [
  {
    titel: 'Was wird knapp?',
    text: 'Alle Artikel mit weniger als 20 Stück, der knappste zuerst.',
    themen: ['WHERE', 'ORDER BY'],
    sql: 'SELECT bezeichnung, bestand\nFROM artikel\nWHERE bestand < 20\nORDER BY bestand;',
  },
  {
    titel: 'Die 3 teuersten Artikel',
    text: 'Sortieren und nach drei Zeilen abschneiden.',
    themen: ['ORDER BY', 'LIMIT'],
    sql: 'SELECT bezeichnung, preis\nFROM artikel\nORDER BY preis DESC\nLIMIT 3;',
  },
  {
    titel: 'Lagerwert je Kategorie',
    text: 'Wie viel Geld liegt in jeder Kategorie im Regal?',
    themen: ['GROUP BY', 'SUM'],
    sql: 'SELECT kategorie,\n       ROUND(SUM(preis * bestand), 2) AS lagerwert\nFROM artikel\nGROUP BY kategorie\nORDER BY lagerwert DESC;',
  },
  {
    titel: 'Bestand-Ampel',
    text: 'Jeder Artikel bekommt einen Status: ausverkauft, knapp oder ok.',
    themen: ['CASE'],
    sql: "SELECT bezeichnung, bestand,\n  CASE\n    WHEN bestand = 0 THEN 'ausverkauft'\n    WHEN bestand < 20 THEN 'knapp'\n    ELSE 'ok'\n  END AS ampel\nFROM artikel\nORDER BY bestand;",
  },
  {
    titel: 'Artikel und ihre Lieferanten',
    text: 'Woher kommt welche Ware?',
    themen: ['JOIN'],
    sql: 'SELECT a.bezeichnung, l.name AS lieferant, l.land\nFROM artikel a\nJOIN lieferanten l ON l.id = a.lieferant_id\nORDER BY l.name;',
  },
  {
    titel: 'Lieferanten ohne Artikel',
    text: 'Bei wem kaufen wir gerade gar nichts?',
    themen: ['LEFT JOIN', 'IS NULL'],
    sql: 'SELECT l.name, l.land, l.bewertung\nFROM lieferanten l\nLEFT JOIN artikel a ON a.lieferant_id = l.id\nWHERE a.id IS NULL;',
  },
  {
    titel: 'Bestellungen mit Kundennamen',
    text: 'Statt der kunde_id steht der Name dabei.',
    themen: ['JOIN'],
    sql: 'SELECT b.id, k.name, b.datum, b.status\nFROM bestellungen b\nJOIN kunden k ON k.id = b.kunde_id\nORDER BY b.datum;',
  },
  {
    titel: 'Umsatz je Kunde',
    text: 'Über vier Tabellen hinweg: Wer hat für wie viel bestellt?',
    themen: ['JOIN', 'GROUP BY'],
    sql: "SELECT k.name,\n       ROUND(SUM(p.menge * a.preis), 2) AS umsatz\nFROM kunden k\nJOIN bestellungen b ON b.kunde_id = k.id\nJOIN positionen p ON p.bestellung_id = b.id\nJOIN artikel a ON a.id = p.artikel_id\nWHERE b.status <> 'storniert'\nGROUP BY k.id\nORDER BY umsatz DESC;",
  },
  {
    titel: 'Bestseller',
    text: 'Welche Artikel gehen am häufigsten raus?',
    themen: ['JOIN', 'SUM', 'LIMIT'],
    sql: 'SELECT a.bezeichnung,\n       SUM(p.menge) AS stueck\nFROM positionen p\nJOIN artikel a ON a.id = p.artikel_id\nGROUP BY a.id\nORDER BY stueck DESC\nLIMIT 5;',
  },
  {
    titel: 'Offene Bestellungen und ihr Wert',
    text: 'Was muss noch raus, und wie viel ist es wert?',
    themen: ['JOIN', 'WHERE', 'GROUP BY'],
    sql: "SELECT b.id, k.name, b.datum,\n       ROUND(SUM(p.menge * a.preis), 2) AS wert\nFROM bestellungen b\nJOIN kunden k ON k.id = b.kunde_id\nJOIN positionen p ON p.bestellung_id = b.id\nJOIN artikel a ON a.id = p.artikel_id\nWHERE b.status = 'offen'\nGROUP BY b.id\nORDER BY b.datum;",
  },
  {
    titel: 'Kunden ohne Bestellung',
    text: 'Wen könnte der Vertrieb mal anrufen?',
    themen: ['LEFT JOIN', 'IS NULL'],
    sql: 'SELECT k.name, k.stadt\nFROM kunden k\nLEFT JOIN bestellungen b ON b.kunde_id = k.id\nWHERE b.id IS NULL;',
  },
  {
    titel: 'Wer verdient am meisten?',
    text: 'Die fünf höchsten Gehälter mit vollem Namen.',
    themen: ['||', 'ORDER BY', 'LIMIT'],
    sql: "SELECT vorname || ' ' || nachname AS name,\n       position, gehalt\nFROM mitarbeiter\nORDER BY gehalt DESC\nLIMIT 5;",
  },
  {
    titel: 'Team je Abteilung',
    text: 'Wie viele Leute arbeiten wo, und was verdienen sie im Schnitt?',
    themen: ['JOIN', 'GROUP BY', 'AVG'],
    sql: 'SELECT a.name AS abteilung,\n       COUNT(m.id) AS personen,\n       ROUND(AVG(m.gehalt), 2) AS durchschnitt\nFROM abteilungen a\nLEFT JOIN mitarbeiter m ON m.abteilung_id = a.id\nGROUP BY a.id\nORDER BY personen DESC;',
  },
  {
    titel: 'Wer ist wessen Chef?',
    text: 'Die Tabelle mitarbeiter verweist auf sich selbst.',
    themen: ['Self-JOIN'],
    sql: "SELECT m.vorname || ' ' || m.nachname AS mitarbeiter,\n       m.position,\n       c.vorname || ' ' || c.nachname AS chef\nFROM mitarbeiter m\nLEFT JOIN mitarbeiter c ON c.id = m.vorgesetzter_id\nORDER BY chef;",
  },
  {
    titel: 'Kunden je Stadt',
    text: 'Wo sitzen unsere Kunden?',
    themen: ['GROUP BY', 'COUNT'],
    sql: 'SELECT stadt, COUNT(*) AS kunden\nFROM kunden\nGROUP BY stadt\nORDER BY kunden DESC, stadt;',
  },
  {
    titel: 'Bestellungen pro Monat',
    text: 'Wie viel war in welchem Monat los?',
    themen: ['strftime', 'GROUP BY'],
    sql: "SELECT strftime('%m', datum) AS monat,\n       COUNT(*) AS bestellungen\nFROM bestellungen\nGROUP BY monat\nORDER BY monat;",
  },
  {
    titel: 'Nachbestellen!',
    text: 'Ausverkaufte Artikel wieder auffüllen.',
    themen: ['UPDATE'],
    aendert: true,
    sql: 'UPDATE artikel\nSET bestand = 100\nWHERE bestand = 0;\n\nSELECT bezeichnung, bestand\nFROM artikel\nORDER BY bestand;',
  },
];
